---
homebrew_taps:
  - hashicorp/tap
  - knqyf263/trivy
  - weaveworks/tap

homebrew_cask_apps:
  - alacritty
  - cloudflare-warp
  - cotEditor
  - deepl
  - discord
  - font-hack-nerd-font
  - font-jetbrains-mono-nerd-font
  - ghostty
  - google-chrome
  - google-cloud-sdk
  - jetbrains-toolbox
  - notion
  - session-manager-plugin
  - slack
  - wireshark
  - zoom
  # Docker alternative
  - orbstack
  # Launcher Tool
  - raycast
  # System Monitor
  - stats

homebrew_packages:
  - act
  - ansible-lint
  - awscli
  - aws-sam-cli
  - bat
  - cdktf
  - cfn-lint
  - cmake
  - colordiff
  - coreutils
  - cloudflare-wrangler
  - deno
  - diffutils
  - duckdb
  # mkpasswd command
  - expect
  - eza
  - fd
  - firebase-cli
  - fish
  - fzf
  - gawk
  # GitHub CLI
  - gh
  - git
  - git-delta
  - gpg
  - terraform-ls
  - httpie
  - infracost
  - jnv
  - jq
  - trivy
  - k6
  - luarocks
  - minikube
  # asdf alternative
  - mise
  - neovim
  - nmap
  - node
  - openssl
  - protobuf
  - python3
  # - reattach-to-user-namespace
  # https://github.com/yamadashy/repomix
  - repomix
  - ripgrep
  - starship
  - stern
  - telnet
  - terraformer
  # - tmux
  - urlview
  - vim
  - wget
  - wxwidgets
  - yarn
  - yq
  # Terminal Multiplexer
  - zellij
